services:
  _defaults:
    autowire: true
    autoconfigure: true

  SomeBdyElse\Typo3ContentModels\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Contract/ContentModel.php'
      - '../Classes/Generation/DependencyInjection'
      - '../Classes/Rendering/DependencyInjection'

  SomeBdyElse\Typo3ContentModels\Generation\Configuration\Configuration:
    factory: ['@SomeBdyElse\Typo3ContentModels\Generation\Configuration\ConfigurationFactory', 'create']

  SomeBdyElse\Typo3ContentModels\Generation\DatabaseSchema\DatabaseSchemaProviderInterface:
    alias: SomeBdyElse\Typo3ContentModels\Generation\DatabaseSchema\ExpectedDatabaseSchemaProvider

  SomeBdyElse\Typo3ContentModels\Generation\Generators\EagerDtoGenerator:
    public: true

  SomeBdyElse\Typo3ContentModels\Generation\Generators\LazyDtoGenerator:
    public: true
    
  SomeBdyElse\Typo3ContentModels\Generation\GenerateModelsCommand:
    public: true

  SomeBdyElse\Typo3ContentModels\Rendering\ContentModelsProcessor:
    tags:
      - { name: 'data.processor', identifier: 'content-models' }

  SomeBdyElse\Typo3ContentModels\Rendering\PageModelProcessor:
    tags:
      - { name: 'data.processor', identifier: 'page-model' }

  SomeBdyElse\Typo3ContentModels\Contract\ContentModelFactoryInterface:
    alias: SomeBdyElse\Typo3ContentModels\Rendering\ContentModelFactory
    public: true

  SomeBdyElse\Typo3ContentModels\Contract\ContentModelRegistryInterface:
    alias: SomeBdyElse\Typo3ContentModels\Rendering\ContentModelRegistry
