services:
  _defaults:
    autowire: true
    autoconfigure: true

  SomeBdyElse\Typo3ContentModels\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Contract/ContentModel.php'
      - '../Classes/Model'
      - '../Classes/Rendering/DependencyInjection'

  SomeBdyElse\Typo3ContentModels\Generation\Configuration\Configuration:
    factory: ['@SomeBdyElse\Typo3ContentModels\Generation\Configuration\ConfigurationFactory', 'create']

  SomeBdyElse\Typo3ContentModels\Generation\DatabaseSchema\DatabaseSchemaProviderInterface:
    alias: SomeBdyElse\Typo3ContentModels\Generation\DatabaseSchema\ExpectedDatabaseSchemaProvider

  SomeBdyElse\Typo3ContentModels\Generation\FieldGeneration\FieldGenerator:
    arguments:
      $handlers:
        - '@SomeBdyElse\Typo3ContentModels\Generation\FieldGeneration\Handler\File'
        - '@SomeBdyElse\Typo3ContentModels\Generation\FieldGeneration\Handler\Relation'
        - '@SomeBdyElse\Typo3ContentModels\Generation\FieldGeneration\Handler\RelationFallback'
        - '@SomeBdyElse\Typo3ContentModels\Generation\FieldGeneration\Handler\RecordPropertyClosure'
        - '@SomeBdyElse\Typo3ContentModels\Generation\FieldGeneration\Handler\StaticSelectSingleEnum'
        - '@SomeBdyElse\Typo3ContentModels\Generation\FieldGeneration\Handler\StaticSelect'
        - '@SomeBdyElse\Typo3ContentModels\Generation\FieldGeneration\Handler\DateTime'
        - '@SomeBdyElse\Typo3ContentModels\Generation\FieldGeneration\Handler\Link'
        - '@SomeBdyElse\Typo3ContentModels\Generation\FieldGeneration\Handler\Fallback'

  SomeBdyElse\Typo3ContentModels\Generation\EagerDtoGenerator:
    public: true
    
  SomeBdyElse\Typo3ContentModels\Generation\GenerateModelsCommand:
    public: true

  SomeBdyElse\Typo3ContentModels\Rendering\PageContentWrapper:
    tags:
      - name: event.listener
        method: __invoke

  SomeBdyElse\Typo3ContentModels\Rendering\PageFetchingProcessor:
    tags:
      - { name: 'data.processor', identifier: 'page' }

  SomeBdyElse\Typo3ContentModels\Contract\ContentModelFactoryInterface:
    alias: SomeBdyElse\Typo3ContentModels\Rendering\ContentModelFactory
    public: true

  SomeBdyElse\Typo3ContentModels\Contract\ContentModelRegistryInterface:
    alias: SomeBdyElse\Typo3ContentModels\Rendering\ContentModelRegistry
