services:
  _defaults:
    autowire: true
    autoconfigure: true

  SomeBdyElse\Typo3ContentModels\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Contract/ContentModel.php'
      - '../Classes/Rendering/DependencyInjection'

  SomeBdyElse\Typo3ContentModels\Generation\Configuration:
    factory: ['@SomeBdyElse\Typo3ContentModels\Generation\ConfigurationFactory', 'create']

  SomeBdyElse\Typo3ContentModels\Generation\DefaultGenerator:
    public: true
    
  SomeBdyElse\Typo3ContentModels\Generation\GenerateModelsCommand:
    public: true

  SomeBdyElse\Typo3ContentModels\Rendering\PageContentWrapper:
    tags:
      - name: event.listener
        method: __invoke

  SomeBdyElse\Typo3ContentModels\Rendering\PageFetchingProcessor:
    tags:
      - { name: 'data.processor', identifier: 'page' }

  SomeBdyElse\Typo3ContentModels\Contract\ContentModelFactoryInterface:
    alias: SomeBdyElse\Typo3ContentModels\Rendering\ContentModelFactory

  SomeBdyElse\Typo3ContentModels\Contract\ContentModelRegistryInterface:
    alias: SomeBdyElse\Typo3ContentModels\Rendering\ContentModelRegistry
